url: https://www.ddsw.kr
baseurl: ""

# Site settings
title: Do Learn Do Run
email: nsw@ddsw.kr
description: "두런두런 소프트웨어 협동조합"

# Team names, titles and social links
people:
- name: 김은미
  pic: 3
  position: kem@ddsw.kr

- name: 나상원
  pic: 2
  position: nsw@ddsw.kr


- name: 박현아
  pic: 3
  position: pha@ddsw.kr


- name: 윤선화
  pic: 3
  position: ysh@ddsw.kr


- name: 윤종석
  pic: 2
  position: yjs@ddsw.kr

     
- name: 이승희
  pic: 3
  position: lsh@ddsw.kr


- name: 이안나
  pic: 3
  position: lan@ddsw.kr

  
- name: 이창후
  pic: 2
  position: lch@ddsw.kr

      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 
# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-slate
